use regex::Regex;
use std::borrow::Cow;
use std::str::FromStr;

use anstream::println;
use miette::Diagnostic;
use once_cell::sync::Lazy;
use owo_colors::OwoColorize;
use rv_ruby::tool_consumable::ToolConsumable;
use tracing::debug;

use rv_ruby::request::RubyRequest;
use rv_ruby::request::Source;

use crate::{
    GlobalArgs,
    config::{Config, RequestedRuby},
};

static RUBY_TOOL_VERSIONS_REGEX: Lazy<Regex> = Lazy::new(|| Regex::new(r"^ *ruby ").unwrap());

#[derive(Debug, thiserror::Error, Diagnostic)]
pub enum Error {
    #[error("No Ruby version request found")]
    NoRubyRequest,
    #[error(transparent)]
    ConfigError(#[from] crate::config::Error),
    #[error(transparent)]
    IoError(#[from] std::io::Error),
    #[error(transparent)]
    VersionError(#[from] rv_ruby::request::RequestError),
}

type Result<T> = miette::Result<T, Error>;

pub(crate) async fn pin(
    global_args: &GlobalArgs,
    request: Option<String>,
    mut resolved: bool,
) -> Result<()> {
    let request = match request {
        None => {
            return show_pinned_ruby(&Config::new(global_args, None)?, resolved).await;
        }
        Some(request) => request,
    };

    if request.trim() == "latest" && !resolved {
        debug!("Input is 'latest'; forcing resolved mode implicitly.");
        resolved = true;
    }

    let ruby_request = RubyRequest::from_str(&request)?;

    let config = &Config::new(global_args, None)?;

    let version = if resolved {
        let resolved = &Config::new(global_args, Some(ruby_request.clone()))?
            .find_matching_remote_ruby()
            .await?;

        resolved.to_tool_consumable_string()
    } else {
        ruby_request.to_tool_consumable_string()
    };

    set_pinned_ruby(config, version)
}

fn set_pinned_ruby(config: &Config, version: String) -> Result<()> {
    let project_dir = match config.requested_ruby {
        RequestedRuby::Project((_, Source::DotToolVersions(ref path))) => {
            let versions = fs_err::read_to_string(path)?;
            let mut new_versions = String::new();
            let mut wrote_ruby = false;

            for line in versions.lines() {
                if let Some(found) = RUBY_TOOL_VERSIONS_REGEX.find(line) {
                    new_versions.push_str(&format!("{}{version}", found.as_str()));
                    wrote_ruby = true;
                } else {
                    new_versions.push_str(line);
                }
                if !wrote_ruby {
                    new_versions.push_str(&format!("ruby {version}"));
                }
                new_versions.push('\n');
            }

            fs_err::write(path, new_versions)?;
            Cow::Borrowed(path)
        }
        RequestedRuby::Project((_, Source::DotRubyVersion(ref path))) => {
            fs_err::write(path, format!("{version}\n"))?;
            Cow::Borrowed(path)
        }
        _ => {
            // For Gemfile.lock source, create a .ruby-version file instead of
            // modifying the lockfile (which is auto-generated by bundler)
            fs_err::write(".ruby-version", format!("{version}\n"))?;
            let path = rv_dirs::canonicalize_utf8(".ruby-version")?;
            Cow::Owned(path)
        }
    };

    println!("{0} pinned to {1}", project_dir.cyan(), version.cyan());

    Ok(())
}

async fn show_pinned_ruby(config: &Config<'_>, resolved: bool) -> Result<()> {
    let (ruby, source) = match &config.requested_ruby {
        RequestedRuby::Project(duple) | RequestedRuby::User(duple) => duple,
        _ => return Err(Error::NoRubyRequest),
    };

    let dir = match source {
        Source::DotToolVersions(path) => Cow::Borrowed(path),
        Source::DotRubyVersion(path) => Cow::Borrowed(path),
        Source::GemfileLock(path) => Cow::Borrowed(path),
    };

    let version = if resolved {
        let resolved_ruby = config.find_matching_remote_ruby().await?;
        resolved_ruby.to_tool_consumable_string()
    } else {
        ruby.to_tool_consumable_string()
    };

    println!("{0} is pinned to {1}", dir.as_ref().cyan(), version.cyan());
    Ok(())
}
