name: Build rv
description: Check out repo, install Rust, cache dependencies, and build rv

runs:
  using: composite
  steps:
    - name: Check out repo
      uses: actions/checkout@v6

    - name: Install Rust
      uses: dtolnay/rust-toolchain@stable

    - name: Cache Rust dependencies
      uses: Swatinem/rust-cache@v2

    - name: Build rv
      shell: bash
      run: cargo build --release --locked --all-features --bin rv
