//! Checks on rv's own installation: the binary, and the directories it writes to.

use camino::Utf8Path;

use super::{Check, ProcessEnv, Section};
use crate::config::Config;

const SECTION: Section = Section::Installation;

pub(super) fn check(config: &Config, env: &ProcessEnv) -> Vec<Check> {
    let mut checks = vec![binary(env)];

    if let Some(rubies) = config.ruby_dirs.first() {
        checks.push(writable("ruby directory", rubies, "rv ruby install"));
    }

    checks.push(writable("cache directory", config.cache.root(), "rv cache"));

    checks
}

/// The `rv` a shell resolves should be the `rv` that is running. When they
/// differ, the shell hook in the user's startup files is driving a different —
/// usually older — build than the one they just invoked.
fn binary(env: &ProcessEnv) -> Check {
    let running = match rv_dirs::current_exe() {
        Ok(exe) => exe,
        Err(err) => {
            return Check::warn(SECTION, "rv", format!("could not be located: {err}"));
        }
    };

    let found = env
        .path()
        .into_iter()
        .map(|dir| dir.join(running.file_name().unwrap_or("rv")))
        .find(|candidate| candidate.is_file());

    match found {
        Some(found) if found == running => Check::ok(SECTION, "rv", rv_dirs::unexpand(&running)),
        Some(found) => Check::warn(
            SECTION,
            "rv",
            format!(
                "running {}, but PATH finds {}",
                rv_dirs::unexpand(&running),
                rv_dirs::unexpand(&found)
            ),
        )
        .suggest(
            "Your shell integration was generated by whichever rv comes first on \
             PATH. Remove the copy you don't want, then reinstall the integration.",
        ),
        None => Check::warn(
            SECTION,
            "rv",
            format!("{} is not on PATH", rv_dirs::unexpand(&running)),
        )
        .suggest("Add its directory to PATH so shells can find it."),
    }
}

/// Can rv create files here? Directories that don't exist yet are fine — rv
/// creates them on demand — as long as an ancestor is writable.
fn writable(name: &'static str, dir: &Utf8Path, command: &str) -> Check {
    let target = dir
        .ancestors()
        .find(|ancestor| ancestor.is_dir())
        .unwrap_or(dir);

    if !can_write_to(target) {
        return Check::fail(
            SECTION,
            name,
            format!("{} is not writable", rv_dirs::unexpand(target)),
        )
        .suggest(format!(
            "Fix its permissions, or point rv elsewhere. `{command} --help` \
             shows the options."
        ));
    }

    let note = if target == dir {
        rv_dirs::unexpand(dir)
    } else {
        format!("{} (will be created)", rv_dirs::unexpand(dir))
    };

    Check::ok(SECTION, name, note)
}

/// Probe by creating a file, because permission bits alone don't account for
/// ACLs, read-only mounts, or Windows.
fn can_write_to(dir: &Utf8Path) -> bool {
    let probe = dir.join(format!(".rv-doctor-{}", std::process::id()));

    match fs_err::File::create(&probe) {
        Ok(_) => {
            let _ = fs_err::remove_file(&probe);
            true
        }
        Err(_) => false,
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::commands::doctor::Status;
    use camino_tempfile::Utf8TempDir;

    #[test]
    fn reports_a_directory_rv_would_create() {
        let temp = Utf8TempDir::new().unwrap();
        let missing = temp.path().join("rubies");

        let check = writable("ruby directory", &missing, "rv ruby install");

        assert_eq!(check.status, Status::Ok);
        assert!(check.message.ends_with("(will be created)"), "{check:?}");
    }

    #[test]
    fn reports_an_existing_directory_plainly() {
        let temp = Utf8TempDir::new().unwrap();

        let check = writable("cache directory", temp.path(), "rv cache");

        assert_eq!(check.status, Status::Ok);
        assert!(!check.message.contains("will be created"), "{check:?}");
    }

    #[cfg(unix)]
    #[test]
    fn fails_on_an_unwritable_directory() {
        use std::os::unix::fs::PermissionsExt as _;

        let temp = Utf8TempDir::new().unwrap();
        let locked = temp.path().join("locked");
        fs_err::create_dir(&locked).unwrap();
        fs_err::set_permissions(&locked, std::fs::Permissions::from_mode(0o500)).unwrap();

        let check = writable("ruby directory", &locked, "rv ruby install");

        // Running as root defeats the permission bits entirely.
        if !can_write_to(&locked) {
            assert_eq!(check.status, Status::Fail);
        }
    }
}
