name: Test

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  merge_group:
    types: [checks_requested]
  workflow_dispatch:

permissions:
  contents: read

env:
  CARGO_INCREMENTAL: 0
  CARGO_TERM_COLOR: always

jobs:
  cargo-deny:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        checks:
          - advisories
          - bans sources
    # Prevent sudden announcement of a new advisory from failing ci:
    continue-on-error: ${{ matrix.checks == 'advisories' }}
    steps:
      - name: Check out repo
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false

      - name: Install cargo-deny
        uses: EmbarkStudios/cargo-deny-action@3fd3802e88374d3fe9159b834c7714ec57d6c979 # v2.0.15
        with:
          command: check ${{ matrix.checks }}

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Check out repo
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false

      - name: Install Rust
        run: rustup show

      - name: Cache dependencies
        uses: Swatinem/rust-cache@c19371144df3bb44fab255c43d04cbc2ab54d1c4 # v2.9.1

      - name: Build rv
        run: bin/build

      - name: Upload rv binary
        uses: actions/upload-artifact@bbbca2ddaa5d8feaa63e36b76fdaad77386f024f # v7.0.0
        with:
          name: rv-binary
          path: target/release/rv

  lint:
    name: Lint (${{ matrix.os }})
    runs-on: ${{ matrix.runs-on }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: linux
            runs-on: ubuntu-latest
          - os: windows
            runs-on: windows-latest
    steps:
      - name: Check out repo
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false

      - name: Install Rust
        run: rustup show

      - name: Cache dependencies
        uses: Swatinem/rust-cache@c19371144df3bb44fab255c43d04cbc2ab54d1c4 # v2.9.1

      - name: Run linters (Unix)
        if: matrix.os == 'linux'
        run: ./bin/lint

      - name: Run linters (Windows)
        if: matrix.os == 'windows'
        run: ./win/lint.ps1

  run-tests:
    name: Run tests
    needs: lint
    runs-on: ${{ matrix.runs-on }}
    strategy:
      fail-fast: false
      matrix:
        runs-on:
          - macos-15-intel # mac-x86
          - macos-latest # mac-arm
          - ubuntu-latest # linux-x86
          - ubuntu-24.04-arm # linux-arm
          - windows-latest # win-x86
          - windows-11-arm # win-arm

    steps:
      - name: Check out repo
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false

      - name: Install additional shells
        if: startsWith(matrix.runs-on, 'ubuntu')
        run: sudo apt-get update && sudo apt-get install -y zsh fish

      - name: Install Rust
        run: rustup show

      - name: Install nextest
        uses: taiki-e/install-action@a1df9120380005ebdc788c62449b841b205541dd # v2.71.0
        with:
          tool: cargo-nextest

      - name: Cache dependencies
        uses: Swatinem/rust-cache@c19371144df3bb44fab255c43d04cbc2ab54d1c4 # v2.9.1

      - name: Build tests
        shell: bash
        run: ./bin/test --no-run

      - name: Run tests
        shell: bash
        run: ./bin/test

      - name: Run Windows integration tests
        if: ${{ startsWith(matrix.runs-on, 'windows') }}
        run: ./win/test-integration.ps1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Run Unix integration tests
        if: ${{ ! startsWith(matrix.runs-on, 'windows') }}
        run: ./bin/test-integration
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  smoke-test:
    name: ${{ matrix.project }}
    needs: build
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        project:
          - diaspora
          - discourse
          - fastlane
          # - gitlab  # Disabled until https://gitlab.com/gitlab-org/gitlab/-/issues/522903 is resolved
          - homebrew
          - huginn
          - llhttp-ffi
          - lobsters
          - local-gemspec
          - mastodon
    steps:
      - name: Check out repo
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false

      - name: Download rv binary
        uses: actions/download-artifact@3e5f45b2cfb9172054b4087a40e8e0b5a5461e7c # v8.0.1
        with:
          name: rv-binary
          path: ~/bin

      - name: Add rv to PATH
        run: chmod +x ~/bin/rv && echo "$HOME/bin" >> $GITHUB_PATH

      - name: rv clean-install for ${{ matrix.project }}
        run: bin/smoke-tests/${{ matrix.project }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
